INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10001,'Samarth', 'Learn Java FullStack', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10002,'Samarth', 'Learn Testing', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10003,'Samarth', 'Learn AWS', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10004,'Samarth', 'Learn DSA', CURRENT_DATE(), false);